IS2_R09/apps/Usuario/urls.py
from django.conf.urls import patterns,url


urlpatterns = patterns('IS2_R09.apps.Usuario.views',
    url(r'^crear_usuario/$','crear_usuario_view', name= 'vista_crear_usuario'),
    url(r'^adm_sesion/$','adm_sesion_view', name= 'vista_adm_sesion'),
    url(r'^mod_datos/$','mod_datos_view', name= 'vista_modificar_datos'),
    url(r'^adm_usuario/$','adm_usuario_view', name= 'vista_adm_usuario'),
    url(r'^modificar/usuario/(?P<id_usuario>.*)/$','modificar_usuario_view', name= 'vista_mod_usuario'),
    url(r'^eliminar/usuario/(?P<id_usuario>.*)/$','eliminar_usuario_view', name= 'vista_eliminar_usuario'),
    url(r'^buscar_usuario/$','buscar_usuario_view', name= 'vista_buscar_usuario'),
    url(r'^consultar/usuario/(?P<id_usuario>.*)/$','consultar_usuario_view', name= 'vista_consultar_usuario'),
)

IS2_R09/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'IS2_R09.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('IS2_R09.apps.home.urls')),
    url(r'^',include('IS2_R09.apps.Usuario.urls')),
    url(r'^',include('IS2_R09.apps.Roles.urls')),
    url(r'^',include('IS2_R09.apps.Proyecto.urls')),
    url(r'^',include('IS2_R09.apps.Flujo.urls')),
    url(r'^',include('IS2_R09.apps.US.urls')),
    url(r'^',include('IS2_R09.apps.Sprint.urls')),
    url(r'^',include('IS2_R09.apps.Comentario.urls')),
    url(r'^',include('IS2_R09.apps.Adjunto.urls')),
    url(r'^',include('IS2_R09.apps.Charts.urls')),
    url(r'^',include('IS2_R09.apps.Release.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT}),
    url(r'^files/', include('db_file_storage.urls')),

)

IS2_R09/apps/Usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class fotoUsuario(models.Model):
    bytes = models.TextField()
    filename = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)
    
class usuario(models.Model):
    def url(self,nombreArchivo):
        ruta = "DatosMultimedia/Usuarios/%s%s" %(self.user.username,nombreArchivo)
        return ruta
    user = models.OneToOneField(User,related_name='usuario')
    foto = models.ImageField(upload_to='Usuario.fotoUsuario/bytes/filename/mimetype',null=True,blank=True)
    telefono = models.CharField(max_length=30)
    
def user_post_save(sender, instance, created, **kwargs):
        if created == True:
            usuari = usuario()
            usuari.user = instance
            usuari.save()
post_save.connect(user_post_save, sender=User)

def user_unicode_patch(self):
    return '%s %s' % (self.first_name, self.last_name)

User.__unicode__ = user_unicode_patch

IS2_R09/apps/Usuario/views.py
# -*- encoding: utf-8 -*-
"""
    Vistas (Views)
    ==============
    
    Módulo que contiene las vistas del módulo L{Home<IS2_R09.apps.Usuario>}, encargadas de controlar las
    distintas operaciones aplicables al mismo.
"""
from django.shortcuts import render_to_response
from django.template import RequestContext
from IS2_R09.apps.Usuario.forms import crear_usuario_form,usuario_form,extension_usuario_form,\
    consultar_usuario_form, buscar_usuario_form
from IS2_R09.apps.Usuario.models import usuario
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from IS2_R09.settings import URL_LOGIN
from django.http.response import HttpResponseRedirect
from IS2_R09.apps.Notificaciones.views import notificar,notificar_creacion_usuario,\
    notificar_mod_usuario, notificar_elim_usuario
# Create your views here.

@login_required(login_url= URL_LOGIN)
def adm_usuario_view(request):
    """
        Administrar Usuario.
        ====================
        
        Vista que controla la interfaz de administración de usuarios.
    """
    users = User.objects.all()
    form = buscar_usuario_form()
    ctx={'usuario':request.user,'users':users,'form':form}
    return render_to_response('usuario/adm_usuario.html',ctx,context_instance=RequestContext(request))

# vista que controla la creacion de usuarios
@login_required(login_url= URL_LOGIN)
def crear_usuario_view(request):
    form = crear_usuario_form()
    if request.method == "POST":
        form = crear_usuario_form(request.POST) # se obtiene los datos del formulario
        if form.is_valid():
            usuario = form.cleaned_data['username']
            nombre = form.cleaned_data['nombre']
            apellido = form.cleaned_data['apellido']
            email =form.cleaned_data['email']
            password_one = form.cleaned_data['password_one']
            password_two = form.cleaned_data['password_two']
            u = User.objects.create_user(username=usuario, email=email,password= password_one,first_name=nombre,last_name=apellido)
            u.save()
            notificar_creacion_usuario(u)
            return render_to_response('usuario/adm_usuario.html', {'mensaje': 'Usuario Creado.','users':User.objects.all(),'icono':'icon-yes.gif','form': buscar_usuario_form()},context_instance=RequestContext(request))
        else:
            ctx = {'form':form}
            return render_to_response('usuario/crear_usuario.html',ctx,context_instance=RequestContext(request))
    ctx = {'form':form}
    return render_to_response('usuario/crear_usuario.html',ctx,context_instance=RequestContext(request))

# esta vista devuelve la interfaz de amdnisitracion de sesion
@login_required(login_url=URL_LOGIN)
def adm_sesion_view(request):
    return render_to_response('usuario/adm_sesion.html',{'usuario':request.user},context_instance=RequestContext(request))

# vista que controla la modificacion de datos del usuario que inicio sesion
@login_required(login_url=URL_LOGIN)
def mod_datos_view(request):
    user_form= usuario_form()
    exten_form=extension_usuario_form()
    if request.method == 'POST':
        # formulario enviado
        if request.FILES:
            user_form = usuario_form(request.POST,instance=request.user)
            perfil_form = extension_usuario_form(request.POST,request.FILES,request.user.usuario)
        #print user_form.username
            if user_form.is_valid() and perfil_form.is_valid():
            # formulario validado correctamente
                actual = request.user.usuario
                actual.telefono = request.POST['telefono']
                actual.foto = request.FILES['foto']
                actual.save()
                i=user_form.save()
                notificar_mod_usuario(request.user)
                return HttpResponseRedirect('/')
        else:
            user_form = usuario_form(request.POST,instance=request.user)
            if user_form.is_valid():
            #formulario validado correctamente
                actual = request.user.usuario
                actual.telefono = request.POST['telefono']
               # actual.foto = request.FILES['foto']
                actual.save()
                i=user_form.save()
                notificar_mod_usuario(request.user)
                return HttpResponseRedirect('/')
    else:
        user_form = usuario_form (instance=request.user)
        exten_form = extension_usuario_form(instance=request.user.usuario)
        return render_to_response('usuario/mod_datos.html', { 'user_form': user_form,  'exten_form': exten_form }, context_instance=RequestContext(request))
    return render_to_response('usuario/mod_datos.html', { 'user_form': user_form,  'exten_form': exten_form }, context_instance=RequestContext(request))

@login_required(login_url=URL_LOGIN)
def modificar_usuario_view(request,id_usuario):
    u= User.objects.get(id=id_usuario)
    user_form= usuario_form()
    exten_form=extension_usuario_form()    
    if request.method == 'POST':
        if request.FILES:
            user_form = usuario_form(request.POST,instance=u)
            perfil_form = extension_usuario_form(request.POST,request.FILES,instance=u.usuario)
        #print user_form.username
            if user_form.is_valid() and perfil_form.is_valid():
            # formulario validado correctamente
                actual = u.usuario
                actual.telefono = request.POST['telefono']
                actual.foto = request.FILES['foto']
                actual.save()
                i=user_form.save()
                notificar_mod_usuario(u)
                return render_to_response('usuario/adm_usuario.html', {'mensaje': 'Usuario modificado.','users':User.objects.all(),'icono':'icon-yes.gif','form': buscar_usuario_form()},context_instance=RequestContext(request))
        else:
            user_form = usuario_form(request.POST,instance=u)
            if user_form.is_valid():
            #formulario validado correctamente
                actual = u.usuario
                actual.telefono = request.POST['telefono']
               # actual.foto = request.FILES['foto']
                actual.save()
                i=user_form.save()
                notificar_mod_usuario(u)
                return render_to_response('usuario/adm_usuario.html', {'mensaje': 'Usuario modificado.','users':User.objects.filter(is_active=True),'icono':'icon-yes.gif','form': buscar_usuario_form()},context_instance=RequestContext(request))
    if request.method == 'GET':
        user_form= usuario_form(initial={
                                         'username':u.username,
                                         'first_name':u.first_name,
                                         'last_name':u.last_name,
                                         'email':u.email,
                                         })
        foto = None
        if u.usuario.foto != '':
            foto=u.usuario.foto.url
        exten_form=extension_usuario_form(instance=u.usuario)
        ctx = { 'user_form': user_form,  'exten_form': exten_form ,'foto':foto}
        return render_to_response('usuario/modificar_usuario.html', ctx, context_instance=RequestContext(request))
    return render_to_response('usuario/modificar_usuario.html', { 'user_form': user_form,  'exten_form': exten_form }, context_instance=RequestContext(request))

#-----------------------------------------------------------------------------------------
@login_required(login_url= URL_LOGIN)
def eliminar_usuario_view(request,id_usuario):
    '''vista que controla la eliminacion de usuarios del sistema'''
    user = User.objects.get(pk=id_usuario)
    if request.method == 'POST':
        user = User.objects.get(pk=id_usuario)
        mail = user.email
        user.delete()
        notificar_elim_usuario(mail)
        users = User.objects.all()
        ctx = {'mensaje': 'Usuario eliminado','users':users,'form': buscar_usuario_form()}
        return render_to_response('usuario/adm_usuario.html', ctx, context_instance=RequestContext(request))
    ctx = {'usuario': user}
    return render_to_response('usuario/eliminar_usuario.html', ctx, context_instance=RequestContext(request))

#----------------------------------------------------------------------------------------------
@login_required(login_url= URL_LOGIN)
def buscar_usuario_view(request):
    form = buscar_usuario_form()
    if(request.method=='POST'):
        form = buscar_usuario_form(request.POST,request.FILES)
        form2 = buscar_usuario_form()
        if form.is_valid():
            busqueda= form.cleaned_data['opciones']
            parametro = form.cleaned_data['busqueda']
            if busqueda== 'nombre':
                u = User.objects.filter(first_name=parametro)
                ctx = {'mensaje': 'Usuarios con nombre %s' %(parametro),'users':u,'form':form2}
                return render_to_response('usuario/adm_usuario.html', ctx, context_instance=RequestContext(request))
            elif busqueda== 'apellido':
                u = User.objects.filter(last_name=parametro)
                ctx = {'mensaje': 'Usuarios con apellido %s' %(parametro),'users':u,'form':form2}
                return render_to_response('usuario/adm_usuario.html', ctx, context_instance=RequestContext(request))
            else :
                u = User.objects.filter(username=parametro)
                ctx = {'mensaje': 'Usuario %s' %(parametro),'users':u,'form':form2}
                return render_to_response('usuario/adm_usuario.html', ctx, context_instance=RequestContext(request))
    ctx = {'form': form}
    return render_to_response('usuario/buscar_usuario.html', ctx, context_instance=RequestContext(request))

#------------------------------------------------------------------------------------------------
@login_required(login_url= URL_LOGIN)
def consultar_usuario_view(request,id_usuario):
    form= consultar_usuario_form()
    if request.method == 'GET':
        u = User.objects.get(pk=id_usuario)

templates/usuario/adm_sesion.html
{% extends "base.html" %}
{% block title %} Administrar Sesion {% endblock %}
{% block content %}
{% load staticfiles %}
<br />
<br />
	<p><a  href = "{% url 'vista_modificar_datos' %}"> Modificar Datos</a></p>
{% endblock %}

templates/usuario/adm_usuario.html
{% extends "base.html" %}
{% block title %} Administrar usuario {% endblock %}
{% block content %}
	<br/>
	<br/>
	<br/>		
	{% load staticfiles %}
<div class="panel row">
	<h4 align="center"><strong>Administración de Usuarios</strong></h4>
	<br />
	<br />
	<div class= "row" data-equalizer>
		
		<div class="large-9 large-centered columns"  data-equalizer-watch>
			<form action="{% url 'vista_buscar_usuario' %}" method='POST'>
				{% csrf_token %}
			 	<dl class="sub-nav" >
  					
					<dd >
						<button title="Nuevo" type="button" class=" radius small success button" name="agregar" onClick="location.href='/crear_usuario/'"><i class="fi-plus"></i></button>
					</dd>
					<dd>
						<p>Buscar por:</p>
					</dd>
					<dd>
					{{form.opciones}}
					</dd>
					<dd >
					{{form.busqueda}}
					</dd>
					<dd >
						<button title="Buscar/Filtrar" class="small info button" type= "submit"><i class="fi-magnifying-glass"></i></button>
					</dd>
					<dd >
						<button title="Mostrar Todos" type="button" class="small info button" name="todos" onClick="location.href='/adm_usuario/'"><i class="fi-torsos-all"></i></button>
					</dd>
				</dl>
			</form>
		</div>
		
	</div>
	<div>
	<table align="center" >
		<thead class="th2">
			<tr>
				<th width="200">UserName</th>
				<th width="200">Nombre</th>
				<th width="200">Apellido</th>
				<th width="200">Teléfono</th>
				<th width="40">Editar</th>
				<th width="40">Eliminar</th>
				<th width="40">Consultar</th>
			</tr>
		</thead>
		{% for u in users %}
		<tbody class="td2">
			<tr>
				<td>{{u.username}}</td>
				<td>{{u.first_name}}</td>
				<td>{{u.last_name}}</td>
				<td>{{u.usuario.telefono}}</td>				
				<td><a href= "/modificar/usuario/{{u.id}}/"><button class="tiny radius success button"><i class="fi-pencil styletrash"></i></button></a></td>
				<td><a href= "/eliminar/usuario/{{u.id}}/"><button class="tiny radius alert button"><i class="fi-trash styletrash"></i></button></a></td>
				<td><a href= "/consultar/usuario/{{u.id}}/"><button class="tiny radius info button"><i class="fi-eye styletrash"></i></button></a></td>
			</tr>
		</tbody>
		
		{% endfor %}
	</table>
	</div>
</div>
	<p align="center"><input class="button" type="button" name="volver_menu" value="Volver a Menú" onClick="location.href='/menu/'"></p>
</div>
{% endblock %}

templates/usuario/buscar_usuario.html
{% extends "base.html" %}
{% block title %} Buscar{% endblock %}
{% block content %}

<form method = 'POST' action = "" >
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Aceptar"></input>
	<input type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_usuario/'">
</form>
{% endblock %}

templates/usuario/consultar_usuario.html
{% extends "base.html" %}
{% block title %} Consultar Usuario{% endblock %}
{% block content %}
<br />
<br />
<h4 align="center"><strong>Datos del Usuario</strong></h4>

<div class="panel row">
		<div class="large-2 columns" >
					<label> Foto
					{% if foto %}
					
						<a class="th" href="{{foto}}">
							<img id="perfil" src = "{{foto}}" width="100px" heigh="500px" >
						</a>
					
					{% else %}
						<a class="th" href="">
							<img id="perfil" src = "/media/images/iconos/no_disponible.png" width="100px" heigh="500px" >
						</a>
					{% endif %}
					</label>					
		</div>
		<div class="large-8 large-centered columns">
				<label>ID:
				{{form.id}}</label>
				<label>User Name:
				{{form.username}}</label>
				<label>Nombre:
				{{form.first_name}}</label>
				<label>Apellido:
				{{form.last_name}}</label>
				<label>Email:
				{{form.email}}</label>
				<label>Telefono:
				{{form.telefono}}</label>
		</div>
	</div>
		<div class="small-7 columns right">
		<p align="center"><input class= "tiny radius alert button" type="button" name="volver" value="Volver" onClick="location.href='/adm_usuario/'"></p>
		</div>
		
{% endblock %}

templates/usuario/crear_usuario.html
{% extends "base.html" %}
{% block title %} Crear Usuario {% endblock %}
{% block content %}
	{% load staticfiles %}
	{% block css %}
		
	{% endblock %}
	<br />
	<br />
	<h4 align="center"><strong>Crear Usuario</strong></h4>
	<div class="panel large-6 large-centered columns">
	<form action = "." method = "POST">
		{% csrf_token %}
		<p><label>Username
		{{ form.username }}</label></p>
		<p><label>Nombre:
		{{ form.nombre }}</label></p>
		
		<p><label>Apellido:
		{{ form.apellido }}</label></p>
		
		<p><label>Email:<br />
		{{ form.email }}</label></p>
		
		<p><label>Password:<br />
		{{ form.password_one }}</label></p>
		
		<p><label>Confirmar Password:<br />
		{{ form.password_two }}</label></p>
		<div class="large-8 right columns">
				<input class = "small radius button" type="submit" value="Guardar"/>
				<input class = "small radius button" type="reset" value="Reset"/>
				<input class = "small radius button alert" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_usuario/'">
		</div>
	</form>
	</div>
{% endblock %}

templates/usuario/eliminar_usuario.html
{% extends "base.html" %}
{% block title %} Modificar Datos{% endblock %}
{% block content %}
<br />
<br />
<h4 align="center"><strong>Eliminar Usuario</strong></h4>
<div class= "panel large-5 large-centered columns">
<p>Esta a punto de eliminar del sistema al siguiente usuario: <strong>{{usuario}}</strong></p>
<p>Por favor confirme la acción</p>
</div>
<div class="large-5 large-centered columns ">
	<form method = 'POST' action = "" >
		{% csrf_token %}
		<div class="small-6 small-centered columns">
			<input class="small radius button" type="submit" value="Aceptar"></input>
			<input class="small radius button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_usuario/'">
		</div>
	</form>
</div>

{% endblock %}

templates/usuario/mod_datos.html
{% extends "base.html" %}
{% block title %} Modificar Datos{% endblock %}
{% block content %}
	{% load staticfiles %}
<br />
<br />

<h4 align="center">Perfil de {{user}}</h4>
<br />
<div class="panel row" data-equalizer>
	
	
			<form method = 'POST' action = "" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="small-3 columns" data-equalizer-watch>
				<label>Foto</label>
					{% if user.usuario.foto %}
						<a class="th" href="/media/{{user.usuario.foto}}">
							<img id="perfil" src = "/media/{{user.usuario.foto}}" width="100px" heigh="500px" >
						</a>
					{% endif %}
					
						<input id="id_foto" type="file" name='foto' ></input>
					
					
				</div>
			<div class="large-8 columns" data-equalizer-watch>
				<div id="formul">
					<p>User Name:<br />
					{{user_form.username}}</p>
					<p>Nombre:<br />
					{{user_form.first_name}}</p>
					<p>Apellido:<br />
					{{user_form.last_name}}</p>
					<p>Email:<br />
					{{user_form.email}}</p>
					<p>Telefono:<br />
					{{exten_form.telefono}}</p>
				</div>
			</div>
				<div class="large-5 right">
					<input class= "tiny radius button" type="submit" value="Guardar Cambios"/>
					<input class= "tiny radius button" type="reset" value="Reset"/>
					<input class= "tiny radius alert button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/menu/'">	
				</div>
			</form>
	</div>

{% endblock %}

templates/usuario/modificar_usuario.html
{% extends "base.html" %}
{% block title %} Modificar Datos{% endblock %}
{% block content %}
	{% load staticfiles %}
	<br />
	<br />
	<h4 align="center"><strong>Editar Usuario</strong></h4>
	<br />
		<div class="panel row" data-equalizer>
	
	
			<form method = 'POST' action = "" enctype="multipart/form-data">
				{% csrf_token %}
				
				<div class="small-3 columns" data-equalizer-watch>
					<label>Foto</label>
					{% if foto %}
						
						<a class="th" href="{{foto}}">
							<img id="perfil" src = "{{foto}}" width="100px" heigh="500px" >
						</a>
						
					{% else %}
						
						<a class="th" href="/media/{{foto}}">
							<img id="perfil" src = "/media/images/iconos/no_disponible.png" width="100px" heigh="500px" >
						</a>
					{% endif %}
					
						<input id="id_foto" type="file" name='foto' ></input>
					
					
				</div>
			<div class="large-8 columns" data-equalizer-watch>
				<div id="formul">
					<p>User Name:<br />
					{{user_form.username}}</p>
					<p>Nombre:<br />
					{{user_form.first_name}}</p>
					<p>Apellido:<br />
					{{user_form.last_name}}</p>
					<p>Email:<br />
					{{user_form.email}}</p>
					<p>Telefono:<br />
					{{exten_form.telefono}}</p>
				</div>
			</div>
				<div class="large-5 right">
					<input class= "tiny radius button" type="submit" value="Guardar Cambios"/>
					<input class= "tiny radius button" type="reset" value="Reset"/>
					<input class= "tiny radius alert button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_usuario/'">	
				</div>
			</form>
	</div>
		
{% endblock %}