IS2_R09/apps/US/urls.py
# -*- encoding: utf-8 -*-

"""
    Modulo que controla las urls de las L{views<IS2_R09.apps.US.views>}   
    @author: Samuel Ruiz,Melissa Bogado,Rafael Ricardo
"""
__docformat__ = "Epytext" 
from django.conf.urls import patterns,url


urlpatterns = patterns('IS2_R09.apps.US.views',
    url(r'^crear_US/$','crear_us_view', name= 'vista_crear_us'),
    url(r'^adm_US/$','adm_us_view', name= 'vista_adm_us'),
    #url(r'^asignar_equipo/proyecto/(?P<id_proyecto>.*)/$','asignar_equipo_view', name= 'vista_asignar_equipo'),
    #url(r'^cantidad_equipo/proyecto/(?P<id_proyecto>.*)/$','cantidad_equipo_view', name= 'vista_cant_equipo'),
    url(r'^modificar/US/(?P<id_us>.*)/$','modificar_us_view', name= 'vista_modificar_us'),
    url(r'^eliminar/US/(?P<id_us>.*)/$','eliminar_us_view', name= 'vista_eliminar_us'),
    url(r'^consultar/US/(?P<id_us>.*)/$','consultar_us_view', name= 'vista_consultar_us'),
    #url(r'^buscar_proyecto/$','buscar_proyecto_view', name= 'vista_buscar_proyecto'),
    url(r'^buscar_US/$','buscar_us_view', name= 'vista_buscar_us'),
    url(r'^infoust/$','info_us', name= 'infoust'),
    url(r'^asignarust/$','asignar_ust', name= 'asignar_ust'),
)

IS2_R09/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'IS2_R09.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('IS2_R09.apps.home.urls')),
    url(r'^',include('IS2_R09.apps.Usuario.urls')),
    url(r'^',include('IS2_R09.apps.Roles.urls')),
    url(r'^',include('IS2_R09.apps.Proyecto.urls')),
    url(r'^',include('IS2_R09.apps.Flujo.urls')),
    url(r'^',include('IS2_R09.apps.US.urls')),
    url(r'^',include('IS2_R09.apps.Sprint.urls')),
    url(r'^',include('IS2_R09.apps.Comentario.urls')),
    url(r'^',include('IS2_R09.apps.Adjunto.urls')),
    url(r'^',include('IS2_R09.apps.Charts.urls')),
    url(r'^',include('IS2_R09.apps.Release.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT}),
    url(r'^files/', include('db_file_storage.urls')),

)

IS2_R09/apps/US/models.py
# -*- encoding: utf-8 -*-

"""
    Modulo que especifíca el modelo a utilizar para los B{User Stories} de los clientes.  
    @author: Samuel Ruiz,Melissa Bogado,Rafael Ricardo
"""
from IS2_R09.apps.Sprint.models import sprint
from IS2_R09.apps.Release.models import release
__docformat__ = "Epytext" 
from django.db import models
from django.contrib.auth.models import User
#from IS2_R09.apps.Flujo.models import flujo
from IS2_R09.apps.Proyecto.models import proyecto
from django.db.models.fields.related import ManyToManyField
from IS2_R09.apps.Adjunto.models import adjunto
from IS2_R09.apps.Comentario.models import comentario
# Create your models here.
class us(models.Model):
    """
        @cvar nombre: Nombre que identifica al B{User Story}
        @type nombre: Varchar
        @cvar PRIORIDADES: Prioridades del B{User Story} (Alta,Media,Baja)
        @cvar descripcion: Breve descripción sobre el B{User Story}
        @type descripcion: Varchar
        @cvar tiempo_estimado: Estimación en horas que consumirá el desarrollo de un B{User Story}
        @type tiempo_estimado: Integer
        @cvar tiempo_trabajado: Horas que consumió el desarrollo de un B{User Story}
        @type tiempo_trabajado: Integer
        @cvar usuario_asignado: Lista de Usuarios asignados al desarrollo del B{User Story}
        @type usuario_asignado: User
        @cvar prioridad: Prioridad del B{User Story}
        @type prioridad: Varchar
        @cvar flujo_asignado: Flujo en el que se desarrolla el B{User Story}
        @type flujo_asignado: Foreign Key
        @cvar proyecto_asociado: Proyecto al que pertenece el B{User Story}
        @type proyecto_asociado: Foreign Key
        
    """
    PRIORIDADES = (
                   ('1', 'Alta'),
                   ('2', 'Media'),
                   ('3', 'Baja'),
                   )
                   
                   
    nombre = models.CharField(max_length=30)
    descripcion = models.TextField(max_length=200)
    tiempo_estimado= models.IntegerField(null=True,blank=True)
    tiempo_trabajado= models.IntegerField(null=True,blank=True,default=0)
    usuario_asignado=models.ManyToManyField(User,null=True,blank=True)
    prioridad=models.CharField(max_length=1, choices=PRIORIDADES)
    #flujo_asignado=models.ForeignKey(flujo,null=True,blank=True,unique=False)
    proyecto_asociado=models.ForeignKey(proyecto,null=True,blank=True,unique=False)
    sprint_asociado= models.ForeignKey(sprint,null=True,blank=True,unique=False)
    adjuntos = ManyToManyField(adjunto,null=True,blank=True)
    comentarios = ManyToManyField(comentario,null=True,blank=True)
    release_asociado = models.ForeignKey(release,null=True,blank=True,default=None)
    def __unicode__(self):
        """
            Método que permite mostrar los objectos de tipo B{User Story}
            por su nombre.
        """
        return self.nombre
    
    def __str__(self):
        return self.nombre

IS2_R09/apps/US/forms.py
# -*- encoding: utf-8 -*-

"""
    Modulo que define los formularios usados en las L{views<IS2_R09.apps.US.views>} de los B{User Stories}.  
    @author: Samuel Ruiz,Melissa Bogado, Rafael Ricardo
"""
__docformat__ = "Epytext" 
from django.forms.models import ModelForm
from IS2_R09.apps.US.models import us
from django import forms


class us_form(ModelForm):
    """
        Formulario creado a partir del modelo de un User Story y utilizado en 
        creación de User Story
    """
    class Meta:
        model = us

class mod_us_form(ModelForm):
    """
        Formulario creado a partir del modelo de un User Story y utilizado en la 
        modificación de User Story
    """
    class Meta:
        model = us
        widgets = {
                   'proyecto_asociado' : forms.Select(attrs={'readonly':'readonly','disable':'disable'}),
                   }
        localized_fields = ('proyecto_asociado',)
        
class buscar_us_form(forms.Form):
    """
        Formulario creado para búsqueda de User Story por nombre
    """
    BUSCAR_POR = {
                  ('nombre','Nombre'),
                  }
    opciones = forms.ChoiceField(label='Buscar Por',required=True,widget=forms.Select(),choices=BUSCAR_POR)
    busqueda = forms.CharField(widget=forms.TextInput())
    
class consultar_form(ModelForm):
    class Meta:
        model = us
        widgets = {
                   'nombre' : forms.TextInput(attrs={'readonly':'readonly','class': 'campos'}),
                   'descripcion' : forms.Textarea(attrs={'readonly':'readonly','class': 'textarea'}), 
                   'tiempo_estimado' : forms.NumberInput(attrs={'readonly':'readonly','class': 'campos'}),
                   'tiempo_trabajado' : forms.NumberInput(attrs={'readonly':'readonly','class': 'campos'}), 
                   'usuario_asiganado': forms.SelectMultiple(attrs={'readonly':'readonly'}),
                   #'prioridad': forms.ChoiceField(attrs={'readonly':'readonly'}),
                   'flujo_asignado': forms.SelectMultiple(attrs={'readonly':'readonly'}),
                   'proyecto_asignado': forms.SelectMultiple(attrs={'readonly': 'readonly'}),
                   }
        
class modificar_form(ModelForm):
    
    class Meta:
        model = us
        exclude = ['usuario_asignado',]
        widgets = {
                   'nombre' : forms.TextInput(attrs={'class': 'campos'}),
                   'descripcion' : forms.Textarea(attrs={'class': 'textarea'}),
                   'tiempo_estimado' : forms.NumberInput(attrs={'class': 'campos'}),
                   'tiempo_trabajado' : forms.NumberInput(attrs={'class': 'campos'}),
                   'prioridad' : forms.TextInput(attrs={'class': 'campos'}),
                   }

IS2_R09/apps/US/views.py
# -*- encoding: utf-8 -*-

"""
    Modulo que controla las operaciones sobre los B{User Stories} de los clientes.  
    @author: Samuel Ruiz,Melissa Bogado,Rafael Ricardo
"""
from IS2_R09.apps.Notificaciones.views import notificar_asignacion_us,\
    notificar_eli_proyecto, notificar_eli_us
from django.http.response import HttpResponse
#from keyring.backend import json
from django.views.decorators.csrf import csrf_exempt
from argparse import Action
from IS2_R09.apps.Sprint.models import sprint
import json
__docformat__ = "Epytext"  

from django.shortcuts import render_to_response
from IS2_R09.apps.US.models import us
from IS2_R09.apps.US.forms import us_form,buscar_us_form, modificar_form,consultar_form

from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from IS2_R09.settings import URL_LOGIN
from IS2_R09.apps.Proyecto.models import Equipo, proyecto
from django.contrib.auth.models import User,Group
from IS2_R09.apps.Flujo.forms import kanban_form
from IS2_R09.apps.Flujo.models import flujo,kanban
@login_required(login_url= URL_LOGIN)
def adm_us_view(request):
    """
        adm_us_view(request)
        Vista que controla la interfaz de administración de B{User Story}
        @param request: Almacena la información del usuario en sesión que ingresa a la interfaz
        de administración de B{User Story}.
        @requires: Estar logeado dentro del sistema.
    """
    ust= us()
    if request.user.is_staff:
        """Si el usuario es administrador se le listan todos los User Story """
        ust = us.objects.all().order_by('prioridad')
        ctx={'uss':ust,'form':buscar_us_form()}
        return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))
    """En caso contrario se le lista solo los User Stories al que esta asignado"""
    ust = us.objects.filter(usuario_asignado=request.user).order_by('prioridad')
    ctx={'uss':ust,'form':buscar_us_form()}
    return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))

#----------------------------------------------------------------------------------------------------------------------------------------------------------
@login_required(login_url= URL_LOGIN)
def crear_us_view(request):
    """
        crear_us_view(request)
        Vista que controla la modificación de un B{User Story}.
        @param request: Almacena la información del usuario que desea crear un B{User Story}.
        @requires: El usuario logeado debe tener rol de administrador o Scrum Master dentro del Proyecto 
        donde creará el B{User Story} 
    """
    form= us_form()
    if request.method == 'POST':
        form = us_form(request.POST)
        if form.is_valid():
            form.save()
            if request.user.is_staff:
                """Si el usuario es administrador se le listan todos los User Stories"""
                ust = us.objects.all().order_by('prioridad')
                ctx={'uss':ust,'form':buscar_us_form()}
                return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))
            else:
                """En caso contrario se le lista solo los user stories que tiene asignado"""
                ust = us.objects.filter(usuario_asignado=request.user).order_by('prioridad')
                ctx={'uss':ust,'form':buscar_us_form()}
                return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))
    equipo = Equipo.objects.filter(miembro=request.user.id)
    role = Group.objects.get(name='Scrum')
    if Equipo.objects.filter(miembro=request.user.id, rol=role).exists():
        print request.user
    #form.fields['usuario_asignado'].queryset= proyecto.objects.filter(id__in=form['proyecto_asociado'].value()).equipo   
    ctx = {'form':form}
    return render_to_response('US/crear_us.html',ctx,context_instance=RequestContext(request))

#------------------------------------
@login_required(login_url= URL_LOGIN)
def modificar_us_view(request,id_us):
    """
        modificar_us_view(request,id_us)
        Vista que controla la modificación de un B{User Story}.
        @param request: Almacena la información del usuario que desea modificar el B{User Story}. 
        @param id_us: Almacena la clave del B{User Story} a modificar.
        @requires: El usuario logeado debe tener rol de administrador , rol de Scrum Master dentro del Proyecto
        o tener asignado el B{User Story} que modificará.
    """
    k= kanban_form()
    if request.method == 'POST':
        user_story = us.objects.get(id=id_us)
        form = us_form(request.POST,instance=user_story)
        ua= user_story.usuario_asignado.all()
        if form.is_valid():
            try:
                kan = kanban.objects.get(us=user_story)
                k = kanban_form(request.POST,instance=kan)
                if k.is_valid():
                    print 'aaaaaaa'
                    kan.us=user_story
                    kan.prioridad = user_story.prioridad
                    f=k.cleaned_data['fluj']
                    fj = flujo.objects.get(id=f.id)
                    sp = form.cleaned_data['sprint_asociado']
                    spu = sprint.objects.get(id=sp.id)
                    
                    spu.tiempo_estimado -= user_story.tiempo_estimado
                    spu.tiempo_estimado += int(form.cleaned_data['tiempo_estimado'])
                    spu.save()
                    form.save()
                    act = fj.actividades.all()[:1].get()
                    kan.actividad = act
                    kan.fluj=fj
                    kan.estado= 'td'
                    
                    notificar_asignacion_us(ua,user_story.nombre)
                    kan.save()
                #kan.fluj= k.cleaned_data['fluj']
                #kan.save()
                    if request.user.is_staff:
                        '''Si el usuario es administrador se le listan todos los us'''
                        ust = us.objects.all().order_by('prioridad')
                        ctx={'uss':ust,'form':buscar_us_form()}
                        return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))
            
                    else:
                        ust = us.objects.filter(usuario_asignado=request.user).order_by('prioridad')
                        ctx={'uss':ust,'form':buscar_us_form()}
                        return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))
            except:
                k = kanban_form(request.POST)
                if k.is_valid():
                    f = k.cleaned_data['fluj']
                    sp = form.cleaned_data['sprint_asociado']
                    spu = sprint.objects.get(id=sp.id)
                    spu.tiempo_estimado -= user_story.tiempo_estimado                    
                    spu.tiempo_estimado += int(form.cleaned_data['tiempo_estimado'])
                    spu.save()
                    fj = flujo.objects.get(id=f.id)
                    act = fj.actividades.all()[:1].get()
                    kan = kanban.objects.create(us=user_story,fluj=k.cleaned_data['fluj'],actividad=act,prioridad = user_story.prioridad)
                    notificar_asignacion_us(ua,user_story.nombre)
                    form.save()
                    #k.save()
                #kan.fluj= k.cleaned_data['fluj']
                #kan.save()
                    if request.user.is_staff:
                        '''Si el usuario es administrador se le listan todos los us'''
                        ust = us.objects.all().order_by('prioridad')
                        ctx={'uss':ust,'form':buscar_us_form()}
                        return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))
            
                    else:
                        ust = us.objects.filter(usuario_asignado=request.user).order_by('prioridad')
                        ctx={'uss':ust,'form':buscar_us_form()}
                        return render_to_response('US/adm_us.html',ctx,context_instance=RequestContext(request))
                
    if request.method=='GET':
        try:
            user_story = us.objects.get(id=id_us)
            kan = kanban.objects.get(us=user_story)
            
            p= proyecto.objects.get(id=user_story.proyecto_asociado.id)
            form =us_form(instance= user_story)
            form.fields['usuario_asignado'].queryset= p.miembro.all()
            #k.fields['us'].queryset = us.objects.get(id=id_us)
            
            #form.fields['flujo_asignado'].queryset= p.flujos.all()
            k =kanban_form(instance=kan)
            k.fields['fluj'].queryset = kan.fluj.all()
            ctx = {'form':form,'k':k}
            return render_to_response('US/modificar_us.html',ctx,context_instance=RequestContext(request))
        except:
            user_story = us.objects.get(id=id_us)
            p= proyecto.objects.get(id=user_story.proyecto_asociado.id)
            form =us_form(instance= user_story)
            form.fields['usuario_asignado'].queryset= p.miembro.all()
            form.fields['sprint_asociado'].queryset= sprint.objects.filter(proyect=p)
            #k.fields['us'].queryset = us.objects.get(id=id_us)
            k.fields['fluj'].queryset = p.flujos.all()
            #form.fields['flujo_asignado'].queryset= p.flujos.all()
            ctx = {'form':form,'k':k}
            return render_to_response('US/modificar_us.html',ctx,context_instance=RequestContext(request))
#---------------------------------------------------------------------------------------------------------------
@login_required(login_url= URL_LOGIN)
def eliminar_us_view(request,id_us):
    """
        eliminar_us_view(request,id_us)
        Vista que controla la eliminación de un B{User Story}.

templates/US/adm_us.html
{% extends "base.html" %}
{% block title %} Administrar US {% endblock %}
{% block content %}
	{% load staticfiles %}
<div>
	<br />
	<br />
	<br />
	<div class="panel row">	
		<h4 align="center"><strong>Administración de User Stories</strong></h4>
	<br />
	<div class="row">
	<div class="large-9 large-centered columns"  data-equalizer-watch>
			<form action="{% url 'vista_buscar_us' %}" method='POST'>
				{% csrf_token %}
			 	<dl class="sub-nav" >
  					
					<dd >
						<button title="Nuevo" type="button" class=" radius small success button" name="agregar" onClick="location.href='/crear_US/'"><i class="fi-plus"></i></button>
					</dd>
					<dd>
						<p>Buscar por:</p>
					</dd>
					<dd>
					{{form.opciones}}
					</dd>
					<dd >
					{{form.busqueda}}
					</dd>
					<dd >
						<button title="Buscar/Filtrar" class="small radius info button" type= "submit"><i class="fi-magnifying-glass"></i></button>
					</dd>
					<dd >
						<button title="Mostrar Todos" type="button" class="small radius info button" name="todos" onClick="location.href='/adm_US/'"><i class="fi-torsos-all"></i></button>
					</dd>
				</dl>
			</form>
		</div>
		</div>
<div>
	<table class="tabless" align="center">
		<thead class="th2">
			<tr>
				<th>Nombre</th>
				<th>Proyecto asociado</th>
				<th>Tiempo estimado</th>
				<th>Tiempo trabajado</th>
				<th>Prioridad</th>
				<th width="40">Editar</th>
				<th width="40">Eliminar</th>
				<th width="40">Consultar</th>
				<th width="40">Comentarios</th>
				<th width="40">Adjuntos</th>
			</tr>
		</thead>
		{% for u in uss %}
		<tbody class="td2">
			<tr>
				<td>{{u.nombre}}</td>
				<td>{{u.proyecto_asociado}}</td>
				<td>{{u.tiempo_estimado}}</td>
				<td>{{u.tiempo_trabajado}}</td>				
				<td>{{u.get_prioridad_display}}</td>
				<td><a href= "/modificar/US/{{u.id}}/"><button class="tiny radius success button"><i class="fi-pencil styletrash"></i></button></a></td>
				<td><a href= "/eliminar/US/{{u.id}}/"><button class="tiny radius alert button"><i class="fi-trash styletrash"></i></button></a></td>
				<td><a href= "/consultar/US/{{u.id}}/"><button class="tiny radius info button"><i class="fi-eye styletrash"></i></button></a></td>
				<td><a href= "/adm_comentario/{{u.id}}/"><button class="tiny radius button">C</button></a></td>
				<td><a href= "/adm_adjunto/{{u.id}}/"><button class="tiny radius button">A</button></a></td>
				
				
			</tr>
		</tbody>
		
		{% endfor %}
	</table>
	<p align="center"><input class="tiny radius button" type="button" name="volver_menu" value="Volver a Menú" onClick="location.href='/menu/'"></p>
</div>
</div>
{% endblock %}

templates/US/consultar_us.html
{% extends "base.html" %}
{% block title %} Consultar US {% endblock %}
{% block content %}
	{% load staticfiles %}
	<br />
	<br />
	<br />
	<h4 align="center">Consulta de US</h4>
	<div class="panel row">
		
	<form action = "." method = "POST">
		{% csrf_token %}
		
			{{ form.non_field_errors }}
			<div class="large-6 large-centered columns"> 
				{{form.nombre.errors}}
				<p>Nombre<br/>
				{{ form.nombre }}
				</p>
				<p>Proyecto asociado<br/>
					<input type="Text" value="{{p}}" readonly></input>
				</p>
				<p>Tiempo estimado(Horas)<br/>
				{{ form.tiempo_estimado }}
				</p>
				<p>Tiempo Trabajado(Horas)<br/>
				{{ form.tiempo_trabajado }}
				</p>
				<p>Usuarios asignados<br/>
				{{ form.usuario_asignado }}
				</p>
				<p>Prioridad<br/>
				{{ form.prioridad }}
				</p>
				<p>Flujo asignado<br/>
				{% if k %}
					<input type="Text" value="{{k}}" readonly></input>
				{% else %}
					<input type="Text" value="Flujo No asignado" readonly></input>
				{% endif %}
				</p>
			
				{{ form.descripcion.errors }}
				<p>Descripción <br/>
				{{ form.descripcion }}</p>
			</div>
			<div align="center" id="bsubmit">
				<input class="small radius button" type="button" name="Cancelar" value="Volver" onClick="location.href='/adm_US/'">
			</div>
		</form>
	</div>
{% endblock %}

templates/US/crear_us.html
{% extends "base.html" %}
{% block title %} Crear US {% endblock %}
{% block content %}
	{% load staticfiles %}
	<br />
	<br />
	<h4 align="center"><strong>Crear User Story</strong></h4>
	<br />
	<div class="panel row">
	<form action = "." method = "POST">
		{% csrf_token %}
		
			{{ form.non_field_errors }}
			<div class="small-6 small-centered columns"> 
				{{form.nombre.errors}}
				<label>Nombre
				{{ form.nombre }}
				</label>
				<label>Proyecto asociado
				{{ form.proyecto_asociado }}
				</label>
				<label>Sprint asociado
				{{ form.sprint_asociado }}
				</label>
				<label>Tiempo estimado(Horas)
				{{ form.tiempo_estimado }}
				</label>
				<label>Tiempo Trabajado(Horas)
				{{ form.tiempo_trabajado }}
				</label>
				<label>Prioridad
				{{ form.prioridad }}
				</label>
			
			
				{{ form.descripcion.errors }}
				<label>Descripción 
				{{ form.descripcion }}</label>
			</div>
			
			<div class="small-6 right">
				<input class = "small radius button" type= "submit" value="Guardar"></input>
				<input class = "small radius button" type="reset" value="Reset"/>
				<input class="small radius alert button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_US/'">
			</div>
		</form>
	</div>
{% endblock %}

templates/US/eliminar_us.html
{% extends "base.html" %}
{% block title%}Eliminar US{% endblock %}
{% block content %}
<br/>
<br />
<h4 align="center"><strong>Eliminar User Story</strong></h4>
<div class= "panel large-5 large-centered columns">
<p>Esta a punto de eliminar del sistema al siguiente US: <strong>{{user_story}}</strong></p>
<p>Por favor confirme la acción</p>
</div>
<div class="large-5 large-centered columns ">
	<form method = 'POST' action = "" >
		{% csrf_token %}
		<div class="small-6 small-centered columns">
			<input class="small radius button" type="submit" value="Aceptar"></input>
			<input class="small radius button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_US/'">
		</div>
	</form>
</div>

{% endblock %}

templates/US/modificar_us.html
{% extends "base.html" %}
{% block title %} Modificar US {% endblock %}
{% block content %}
	{% load staticfiles %}
	<br />
	<br />
	<h4 align="center"><strong>Modificar User Story</strong></h4>
	<br />
	<div class="panel row">
	<form action = "." method = "POST">
		{% csrf_token %}
		
			{{ form.non_field_errors }}
			<div class="small-6 small-centered columns"> 
				{{form.nombre.errors}}
				<p>Nombre<br/>
				{{ form.nombre }}
				</p>
				<p>Proyecto asociado<br/>
				{{ form.proyecto_asociado }}
				</p>
				<p>Tiempo estimado(Horas)<br/>
				{{ form.tiempo_estimado }}
				</p>
				<p>Tiempo Trabajado(Horas)<br/>
				{{ form.tiempo_trabajado }}
				</p>
				<p>Usuarios asignados<br/>
				{{ form.usuario_asignado }}
				</p>
				<p>Prioridad<br/>
				{{ form.prioridad }}
				</p>
				<label>Sprint asociado
				{{ form.sprint_asociado }}
				</label>
				<p>Flujo asignado<br/>
				{{ k.fluj }}
				</p>
			
				{{ form.descripcion.errors }}
				<p>Descripción <br/>
				{{ form.descripcion }}</p>
			</div>
			
			<div class="small-6 right">
				<input class = "small radius button" type= "submit" value="Guardar"></input>
				<input class = "small radius button" type="reset" value="Reset"/>
				<input class="small radius alert button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_US/'">
			</div>
	</div>
{% endblock %}