IS2_R09/apps/Flujo/urls.py
# -*- encoding: utf-8 -*-
"""
    URLS
    ====
    
    Modulo que controla las urls de las L{Vistas<IS2_R09.apps.Flujo.views>} utilizadas en
    L{Flujo<IS2_R09.apps.Flujo>}.
"""
from django.conf.urls import patterns,url


urlpatterns = patterns('IS2_R09.apps.Flujo.views',
    url(r'^crear_flujo/(?P<nuevo>.*)/$','crear_flujo_view', name= 'vista_crear_flujo'),
    url(r'^adm_flujo/$','adm_flujo_view', name= 'vista_adm_flujo'),
    url(r'^crear_actividad/(?P<nuevo>.*)/$','crear_actividad_view', name= 'vista_crear_actividad'),
    #url(r'^crear_actividad/$','crear_actividad_view', name= 'vista_crear_actividad'),
    url(r'^crear_actividad/flujo/(?P<id_flujo>.*)/$','crear_actividad_from_mod_view', name= 'vista_crear_actividad_modflujo'),
    #url(r'^asignar_equipo/proyecto/(?P<id_proyecto>.*)/$','asignar_equipo_view', name= 'vista_asignar_equipo'),
    #url(r'^cantidad_equipo/proyecto/(?P<id_proyecto>.*)/$','cantidad_equipo_view', name= 'vista_cant_equipo'),
    url(r'^modificar/flujo/(?P<id_flujo>.*)/$','modificar_flujo_view', name= 'vista_modificar_flujo'),
    url(r'^eliminar/flujo/(?P<id_flujo>.*)/$','eliminar_flujo_view', name= 'vista_eliminar_flujo'),
    url(r'^consultar/flujo/(?P<id_flujo>.*)/$','consultar_flujo_view', name= 'vista_consultar_flujo'),
    url(r'^buscar_flujo/$','buscar_flujo_view', name= 'vista_buscar_flujo'),
    url(r'^sort/$', 'sort', name='sort'),
)

IS2_R09/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'IS2_R09.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('IS2_R09.apps.home.urls')),
    url(r'^',include('IS2_R09.apps.Usuario.urls')),
    url(r'^',include('IS2_R09.apps.Roles.urls')),
    url(r'^',include('IS2_R09.apps.Proyecto.urls')),
    url(r'^',include('IS2_R09.apps.Flujo.urls')),
    url(r'^',include('IS2_R09.apps.US.urls')),
    url(r'^',include('IS2_R09.apps.Sprint.urls')),
    url(r'^',include('IS2_R09.apps.Comentario.urls')),
    url(r'^',include('IS2_R09.apps.Adjunto.urls')),
    url(r'^',include('IS2_R09.apps.Charts.urls')),
    url(r'^',include('IS2_R09.apps.Release.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT}),
    url(r'^files/', include('db_file_storage.urls')),

)

IS2_R09/apps/Flujo/models.py
# -*- encoding: utf-8 -*-
"""
    Modelos
    =======
    
    Módulo que define la estructura de un L{Flujo<IS2_R09.apps.Flujo>} y como se guardará en la
    base de datos.
"""
from django.db import models
# Create your models here.

#----------------------------------------------------------------------------------------------
class actividad(models.Model):
    """
        Modelo de Actividad
        ===================
        Clase que define una actividad de un L{Flujo<IS2_R09.apps.Flujo>}.
        @cvar nombre: Nombre de la actividad.
        @type nombre: Varchar
    """
    nombre = models.CharField(max_length=30,unique=False)
    order = models.PositiveIntegerField(default=0)
    
    class Meta:
        ordering = ['order']
    def __unicode__(self):
        """
            Método que permite representar los objectos de la clase L{Actividad<IS2_R09.apps.Flujo.models.actividad>}
            mediante su nombre.
            @return: Varchar
        """
        return self.nombre
#----------------------------------------------------------------------------------------------
class flujo(models.Model):
    """
        Model de Flujo
        ==============
        
        Clase que define un B{Flujo}
        @cvar nombre: Nombre asignado al Flujo.
        @type nombre: Varchar
        @cvar actividades: Lista de actividades que tiene el B{Flujo}, mediante la relación 
        ManytoMan(Muchos a muchos) con L{Actividad<IS2_R09.apps.Flujo.models.actividad>}
        @type actividades: L{Actividad<IS2_R09.apps.Flujo.models.actividad>}
    """
    nombre = models.CharField(max_length=30)
    actividades = models.ManyToManyField(actividad)
    user_stories = models.ManyToManyField('US.us',through='kanban',related_name='userstories',null=True,blank=True)
    def __unicode__(self):
        """
            Método que permite representar los objectos de la clase L{Flujo<IS2_R09.apps.Flujo.models.actividad>}
            mediante su nombre.
            @return: Varchar
        """
        return self.nombre
 
class kanban(models.Model):
    """
        Modelo de Kanban
        ================
        
    """
    ESTADOS = (
               ('td','to do'),
               ('dg', 'doing'),
               ('de', 'done'),
               )
    fluj = models.ForeignKey(flujo,related_name='flujo',null=True,blank=True)
    actividad = models.ForeignKey(actividad,related_name='actividad',null=True,blank=True)
    us = models.ForeignKey('US.us',related_name='user_story',null=True,blank=True)
    estado = models.CharField(max_length=2,choices=ESTADOS,default='td',null=True,blank=True)
    prioridad = models.CharField(max_length=1,null=True,blank=True)
    class Meta:
        ordering = ['prioridad']
    
'''
ESTADOS = (
               ('td','to do'),
               ('dg', 'doing'),
               ('de', 'done'),
               )
    nombre = models.CharField(max_length=30)
    estado = models.CharField(max_length=2,choices=ESTADOS)
    '''

IS2_R09/apps/Flujo/views.py
# -*- encoding: utf-8 -*-

"""
    Vistas (Views)
    ==============
    
    Módulo que contiene las vistas del módulo L{Flujo<IS2_R09.apps.Flujo>}, encargadas de controlar las
    distintas operaciones aplicables al mismo.
"""

from django.shortcuts import render, render_to_response, get_object_or_404
from IS2_R09.apps.Flujo.models import flujo,actividad
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from IS2_R09.settings import URL_LOGIN
from IS2_R09.apps.Flujo.forms import flujo_form,buscar_flujo_form,actividad_form,consultar_form
from django.contrib.redirects.models import Redirect
from django.http.response import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import simplejson

@login_required(login_url= URL_LOGIN)
def adm_flujo_view(request):
    """
        adm_flujo_view(request)
        Administración de Flujos.
        =========================
        
        Vista que controla la interfaz de administracion de flujos
        @param request: Almacena información concerniente a la consulta realizada
        como el usuario que la realiza etc.
    """
    flujos= flujo()
    if request.user.is_staff:
        flujos = flujo.objects.all()
        ctx={'flujos':flujos,'form':buscar_flujo_form()}
        return render_to_response('flujo/adm_flujo.html',ctx,context_instance=RequestContext(request))
    
#----------------------------------------------------------------------------------------------------------------------------------------------------------

@login_required(login_url= URL_LOGIN)
def crear_flujo_view(request,nuevo):
    """
        crear_flujo_view(request)
        Administración de Flujos.
        =========================
        
        Vista que controla la interfaz de creación de flujos
        @param request: Almacena información concerniente a la consulta realizada
        como el usuario que la realiza etc.
    """
    form= flujo_form()
    if request.method == 'POST':
        form = flujo_form(request.POST)
        if form.is_valid():
            form.save()
            if request.user.is_staff:
                flujos = flujo.objects.all()
                ctx={'flujos':flujos,'mensaje':'Flujo creado','form':buscar_flujo_form()}
                return HttpResponseRedirect('/adm_flujo/',ctx)
    try:
        if nuevo== 'n':
            a = actividad.objects.latest('id')
            nuevo = str(a.id)
            form.fields['actividades'].queryset= actividad.objects.filter(id__gt=a.id)
        form.fields['actividades'].queryset= actividad.objects.filter(id__gt=int(nuevo))
        ctx = {'form':form,'nuevo':nuevo}
        return render_to_response('flujo/crear_flujo.html',ctx,context_instance=RequestContext(request))
    except:
        nuevo = str('0')
        ctx = {'form':form,'nuevo':nuevo}
        return render_to_response('flujo/crear_flujo.html',ctx,context_instance=RequestContext(request))
#----------------------------------------------------------------------------------------------------------------------------------------------------------

@login_required(login_url= URL_LOGIN)
def crear_actividad_view(request,nuevo):
    """
        crear_actividad_view(request)
        Crear Actividad para Flujo.
        ===========================
        
        Vista que controla la interfaz de creación de actividades paraflujos
        @param request: Almacena información concerniente a la consulta realizada
        como el usuario que la realiza etc.
    """
    form = actividad_form()
    if request.method == 'POST':
        form = actividad_form(request.POST)
        if form.is_valid():
            form.save()
            form= flujo_form()
            ctx = {'form':form}
            return HttpResponseRedirect('/crear_flujo/%s'%(nuevo),ctx)
    ctx = {'form':form,'nuevo':nuevo}
    return render_to_response('actividad/crear_actividad.html',ctx,context_instance=RequestContext(request))

#---------------------------------------------------------------------------------------------------------------
@login_required(login_url= URL_LOGIN)
def eliminar_flujo_view(request,id_flujo):
    """
        eliminar_flujo_view(request,id_flujo)
        Eliminación de Flujos.
        ======================
        
        Vista que controla la eliminación de flujos
        @param request: Almacena información concerniente a la consulta realizada.
        @param id_flujo: ID del flujo a eliminar.
    """
    fluj = flujo.objects.get(pk=id_flujo)
    if request.method == 'POST':
        fluj.delete()
        if request.user.is_staff:
            flujos = flujo.objects.all()
            ctx={'flujos':flujos,'form':buscar_flujo_form()}
            return HttpResponseRedirect('/adm_flujo/',ctx)
                
    ctx = {'flujo': fluj}
    return render_to_response('flujo/eliminar_flujo.html', ctx, context_instance=RequestContext(request))

#---------------------------------------------------------------------------------------------------------------

@login_required(login_url= URL_LOGIN)
def modificar_flujo_view(request,id_flujo):
    """
        modificar_flujo_view(request,id_flujo)
        Modificación de Flujos.
        =======================
        
        Vista que controla la modificación de datos de los flujos
        @param request: Almacena información concerniente a la consulta realizada como el usuario
        que la realiza, los datos del formulario, etc.
        @param id_flujo: ID del flujo a modificar.
    """
    if request.method == 'POST':
        fluj = flujo.objects.get(id=id_flujo)
        form = flujo_form(request.POST,instance=fluj)
        if form.is_valid():
            form.save()
            flujos = flujo.objects.all()
            ctx={'flujos':flujos,'form':buscar_flujo_form()}
            return HttpResponseRedirect('/adm_flujo/',ctx)
    if request.method=='GET':
        
        fluj = flujo.objects.get(id=id_flujo)
        form = flujo_form(instance= fluj)
        form.fields['actividades'].queryset= fluj.actividades.all()
        actividades = fluj.actividades.all()
        list= zip(form['actividades'],actividades)
        ctx = {'form':form,'id':id_flujo,'list':list}
        return render_to_response('flujo/modificar_flujo.html',ctx,context_instance=RequestContext(request))
    
#----------------------------------------------------------------------------------------------------------------------------------------------------------
@login_required(login_url= URL_LOGIN)
def crear_actividad_from_mod_view(request,id_flujo):
    """
        crear_actividad_view(request,id_flujo)
        Crear Actividad para Flujo.
        ===========================
        
        Vista que controla la interfaz de creación de actividades para flujos desde la modificacion
        @param request: Almacena información concerniente a la consulta realizada
        como el usuario que la realiza etc.
        @param id_flujo: Flujo que se estaba modificando
    """
    form = actividad_form()
    if request.method == 'POST':
        form = actividad_form(request.POST)
        if form.is_valid():
            form.save()
            fluj = flujo.objects.get(id=id_flujo)
            form = flujo_form(instance= fluj)
            form.fields['actividades'].queryset= fluj.actividades.all()
            actividades = fluj.actividades.all()
            list= zip(form['actividades'],actividades)
            print 'a'
            ctx = {'form':form,'id':id_flujo,'list':list}
            return HttpResponseRedirect('/modificar/flujo/%s'%(id_flujo),ctx)
    ctx = {'form':form}
    return render_to_response('actividad/crear_actividad.html',ctx,context_instance=RequestContext(request))

#---------------------------------------------------------------------------------------------------------------
    
@login_required(login_url= URL_LOGIN)
def consultar_flujo_view(request,id_flujo):
    """
        consultar_flujo_view(request,id_flujo)
        Consulta de Flujo.
        ==================
        
        Vista que controla la consuta de datos de los flujos
        @param request: Almacena información concerniente a la consulta realizada.
        @param id_flujo: ID del flujo a eliminar.
    """
    if request.method=='GET':
        fluj = flujo.objects.get(id=id_flujo)
        form = consultar_form(instance= fluj)
        form.fields['actividades'].queryset=fluj.actividades.all()
        ctx = {'form':form}
        return render_to_response('flujo/consultar_flujo.html',ctx,context_instance=RequestContext(request))
#------------------------------------------------------------------------------------------------------------

@login_required(login_url= URL_LOGIN)
def buscar_flujo_view(request):
    """
        buscar_flujo_view(request)
        Búsqueda de Flujos.
        ===================
        
        Vista que controla la busqueda de flujos a traves del nombre.
        @param request: Almacena información concerniente a la consulta realizada.
    """
    form = buscar_flujo_form()
    if(request.method=='POST'):
        form = buscar_flujo_form(request.POST)
        form2 = buscar_flujo_form()
        if form.is_valid():
            busqueda= form.cleaned_data['opciones']
            parametro = form.cleaned_data['busqueda']
            if busqueda== 'nombre':
                p = flujo.objects.filter(nombre=parametro)
                ctx = {'mensaje': 'Flujo con nombre %s' %(parametro),'flujos':p,'form':form2}
                return render_to_response('flujo/adm_flujo.html', ctx, context_instance=RequestContext(request))
                                
    ctx = {'form': form}
    return render_to_response('proyecto/adm_flujo.html', ctx, context_instance=RequestContext(request))
@csrf_exempt
def sort(request):
    lista= request.POST.getlist('act[]')
    for index, act_pk in enumerate(request.POST.getlist('act[]')):
        act = get_object_or_404(actividad, pk=int(str(act_pk)))

templates/flujo/adm_flujo.html
{% extends "base.html" %}
{% block title %} Administrar Flujo {% endblock %}
{% block content %}
	{% load staticfiles %}
<div>
	<br />
	<br />
	<br />
	<div class="panel row">	
	<h4 align="center"><strong>Administración de Flujos</strong></h4>
	<br />
	<div class="row">
	<div class="large-9 large-centered columns"  data-equalizer-watch>
			<form action="{% url 'vista_buscar_flujo' %}" method='POST'>
				{% csrf_token %}
			 	<dl class="sub-nav" >
  					
					<dd >
						<button title="Nuevo" type="button" class=" radius small success button" name="agregar" onClick="location.href='/crear_flujo/n'"><i class="fi-plus"></i></button>
					</dd>
					<dd>
						<p>Buscar por:</p>
					</dd>
					<dd>
					{{form.opciones}}
					</dd>
					<dd >
					{{form.busqueda}}
					</dd>
					<dd >
						<button title="Buscar/Filtrar" class="small radius info button" type= "submit"><i class="fi-magnifying-glass"></i></button>
					</dd>
					<dd >
						<button title="Mostrar Todos" type="button" class="small radius info button" name="todos" onClick="location.href='/adm_flujo/'"><i class="fi-torsos-all"></i></button>
					</dd>
				</dl>
			</form>
		</div>
		</div>
<div>
	<table align="center" class="tabless">
		<thead class="th2">
			<tr>
				<th width="200">ID</th>
				<th width="200>Nombre</th>
				<th width="40">Editar</th>
				<th width="40">Eliminar</th>
				<th width="40">Consultar</th>
			</tr>
		</thead>
		{% for f in flujos %}
		<tbody class="td2">
			<tr>
				<td>{{f.id}}</td>
				<td>{{f.nombre}}</td>
				<td><a href= "/modificar/flujo/{{f.id}}/"><button class="tiny radius success button"><i class="fi-pencil styletrash"></i></button></a></td>
				<td><a href= "/eliminar/flujo/{{f.id}}/"><button class="tiny radius alert button"><i class="fi-trash styletrash"></i></button></a></td>
				<td><a href= "/consultar/flujo/{{f.id}}/"><button class="tiny radius info button"><i class="fi-eye styletrash"></i></button></a></td>
			</tr>
		</tbody>
		
		{% endfor %}
	</table>
	<p align="center"><input class="tiny radius button" type="button" name="volver_menu" value="Volver a Menú" onClick="location.href='/menu/'"></p>
</div>
</div>
{% endblock %}

templates/flujo/consultar_flujo.html
{% extends "base.html" %}
{% block title %} Consultar Flujo {% endblock %}
{% block content %}
	{% load staticfiles %}
	<br />
	<br />
	
	<h4 align="center"><strong>Consulta de Flujo</strong></h4>
	<div class="panel row ">
	<form action = "." method = "POST">
		{% csrf_token %}
		
			{{ form.non_field_errors }}
			<div class="large-6 large-centered columns"> 
				{{form.nombre.errors}}
				<label>Nombre
				{{ form.nombre }}
				</label>
				<label>Actividades
				{{ form.actividades }}</label>
				
			</div>
			<div class="large-2 right columns">
				<p align="auto"><input class="small radius button" type="button" name="Cancelar" value="Volver" onClick="location.href='/adm_flujo/'"></p>
			</div>
		</form>
	</div>
{% endblock %}

templates/flujo/crear_flujo.html
{% extends "base.html" %}
{% block title %} Crear Flujo {% endblock %}
{% block content %}
	{% load staticfiles %}
	<br />
	<br />
	<br />
	<h4 align="center"><strong>Crear flujo</strong></h4>
	<div class="panel row">
	<form action = "." method = "POST">
		{% csrf_token %}
		
			{{ form.non_field_errors }}
			<div class="medium-6 medium-centered columns"> 
				{{form.nombre.errors}}
				<p>Nombre<br/>
				{{ form.nombre }}
				</p>
				<p>Actividades<br/>
				{{ form.actividades }}
				</p>
				<label for="agregar">Agregar Actividad</label>
				<button class="tiny radius success" type="button" name="agregar" onClick="location.href='/crear_actividad/{{nuevo}}'"><i class="fi-plus"></i></button>
				
			</div>
			<div class="small-6 right">
				<input class = "small radius button" type= "submit" value="Guardar"></input>
				<input class = "small radius button" type="reset" value="Reset"/>
				<input class="small radius alert button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_flujo/'">
			</div>
		</form>
	</div>
{% endblock %}

templates/flujo/eliminar_flujo.html
{% extends "base.html" %}
{% block title%}Eliminar Flujo{% endblock %}
{% block content %}

<br />
<br />
<h4 align="center"><strong>Eliminar Flujo</strong></h4>
<div class= "panel large-5 large-centered columns">
<p>Esta a punto de eliminar del sistema al siguiente flujo: <strong>{{flujo}}</strong></p>
<p>Por favor confirme la acción</p>
</div>
<div class="large-5 large-centered columns ">
	<form method = 'POST' action = "" >
		{% csrf_token %}
		<div class="small-6 small-centered columns">
			<input class="small radius button" type="submit" value="Aceptar"></input>
			<input class="small radius button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_flujo/'">
		</div>
	</form>
</div>

{% endblock %}

templates/flujo/modificar_flujo.html
{% extends "base.html" %}
{% block extra_head %}

{% endblock extra_head %}
{% block title %} Modificar Flujo {% endblock %}
{% block content %}
	{% load staticfiles %}
	<br />
	<br />
	<h4 align="center"><strong>Modificar Flujo</strong></h4>
	<br />
	<div class="panel row">
	<form action = "." method = "POST">
		{% csrf_token %}
		
			{{ form.non_field_errors }}
			<div class="small-6 small-centered columns"> 
				{{form.nombre.errors}}
				<label>Nombre
				{{ form.nombre }}
				</label>
				
				<label>Actividades. Puede cambiar el orden arrastrandolas</label>
				
				<ul id="id_actividades">
    			{% for a,ac in list %}
      				<li id="act_{{ac.id}}">
        				{{ a }}
        			</li>
      			
    		{% endfor %}
				</ul>
				<label for="agregar">Agregar actividad</label>
				<button class="tiny sucess radius button" type="button" name="agregar" onClick="location.href='/crear_actividad/flujo/{{id}}'"><i class="fi-plus"></i></button>
				
			</div>
			<div class="small-6 right">
				<input class = "small radius button" type= "submit" value="Guardar"></input>
				<input class = "small radius button" type="reset" value="Reset"/>
				<input class="small radius alert button" type="button" name="Cancelar" value="Cancelar" onClick="location.href='/adm_flujo/'">
			</div>
		</form>
	</div>
{% endblock %}